python3 ../rand.py 2 ../datasets/c2ds1-2spReal.clu saidas/espiral2.clu espiral2
python3 ../rand.py 3 ../datasets/c2ds1-2spReal.clu saidas/espiral3.clu espiral3
python3 ../rand.py 4 ../datasets/c2ds1-2spReal.clu saidas/espiral4.clu espiral4
python3 ../rand.py 5 ../datasets/c2ds1-2spReal.clu saidas/espiral5.clu espiral5
python3 ../rand.py 2 ../datasets/c2ds3-2gReal.clu saidas/bolas2.clu bolas2
python3 ../rand.py 3 ../datasets/c2ds3-2gReal.clu saidas/bolas3.clu bolas3
python3 ../rand.py 4 ../datasets/c2ds3-2gReal.clu saidas/bolas4.clu bolas4
python3 ../rand.py 5 ../datasets/c2ds3-2gReal.clu saidas/bolas5.clu bolas5
python3 ../rand.py 8 ../datasets/monkeyReal1.clu saidas/monkey5.clu monkey5
python3 ../rand.py 8 ../datasets/monkeyReal1.clu saidas/monkey6.clu monkey6
python3 ../rand.py 8 ../datasets/monkeyReal1.clu saidas/monkey7.clu monkey7
python3 ../rand.py 8 ../datasets/monkeyReal1.clu saidas/monkey8.clu monkey8
python3 ../rand.py 9 ../datasets/monkeyReal1.clu saidas/monkey9.clu monkey9
python3 ../rand.py 10 ../datasets/monkeyReal1.clu saidas/monkey10.clu monkey10
python3 ../rand.py 11 ../datasets/monkeyReal1.clu saidas/monkey11.clu monkey11
python3 ../rand.py 12 ../datasets/monkeyReal1.clu saidas/monkey12.clu monkey12